import std;
import parser;

// // Prepends a prefix (shocked emoji) to the start of each line
// std::string prepend(std::string target, const std::string& prefix) {
// 	target.insert(0, prefix);

// 	size_t pos = target.find('\n');

// 	while (pos != std::string::npos) {
// 		// Don't insert it after the last newline
// 		if (pos + 1 < target.size()) {
// 			target.insert(pos + 1, prefix);
// 		}

// 		pos = target.find('\n', pos + prefix.size() + 1);
// 	}

// 	return target;
// }

// // Trims all leading spaces, tabs from the start of each line.
// std::string trim(std::string target) {
// 	size_t start = 0;

// 	while (start < target.size()) {
// 		auto end = start;

// 		while (end < target.size() && (target[end] == ' ' || target[end] == '\t')) {
// 			++end;
// 		}
// 		target.erase(start, end - start);

// 		size_t newline_pos = target.find('\n', start);
// 		// We've done every line
// 		if (newline_pos == std::string::npos) {
// 			break;
// 		}
// 		start = newline_pos + 1;
// 	}
// 	return target;
// }

std::string discriminate_clang(std::string_view content) {
	return std::format("\n#ifdef MAYQUILL_ICE\n{}\n#endif\n", content);
}

std::string pascal_to_snake(std::string target) {
	target[0] = std::tolower(target[0]);
	for (int i = 1; i < target.length(); i++) {
		if (std::isupper(target[i])) {
			target[i] = std::tolower(target[i]);
			target.insert(i, 1, '_');
			i++; // skip the next one, because we just inserted there
		}
	}

	return target;
}

void add_header(std::string& target) {
	target += "/* Generated by MayQuill, godspeed */\n";
}

void write_file(std::string name, std::string content) {
	std::ofstream file(std::format("build/generated-modules/{}", pascal_to_snake(name)));
	std::print(file, "{}", content);
}

void add_since(std::string& content, std::uint32_t since) {
	content += std::format("        static constexpr since = {};\n", since);
}

int main() {
	auto protocols = parser::get_protocols();

	// Write the primary mayquill interface
	{
		std::string content = "";
		add_header(content);
		content += "export module mayquill;\n"
				   "export import :server;\n"
				   "export import :logger;\n\n";

		for (auto& protocol : protocols) {
			for (auto& interface : protocol.interfaces) {
				content += std::format("export import :{}.{};\n", protocol.name, interface.name);
			}
		}

		write_file("mayquill.cppm", std::move(content));
	}

	// Write the interface, a variant of all the objects
	{
		std::string content = "";
		add_header(content);
		content += "module mayquill:interface;\n"
				   "import std;\n\n";

		// Write the imports
		for (auto& protocol : protocols) {
			for (auto& interface : protocol.interfaces) {
				content += std::format("import :{}.{};\n", protocol.name, interface.name);
			}
		}

		// Write the using Interface
		content += "\nnamespace mayquill {\n"
				   "using Interface = std::variant<";
		for (auto& protocol : protocols) {
			for (std::size_t i = 0; i < protocol.interfaces.size(); ++i) {
				content += parser::snake_to_pascal(protocol.interfaces[i].name);
				if (i == protocol.interfaces.size() - 1) {
					continue;
				}
				content += ", ";
			}
		}
		content += ">;\n};";
		write_file("interface.cppm", std::move(content));
	}

	// Write the individual interfaces
	for (auto& protocol : protocols) {
		for (auto& interface : protocol.interfaces) {
			std::string struct_name = parser::snake_to_pascal(interface.name);

			{
				std::string content = "";
				add_header(content);
				content += std::format(
					// "module;\n"
					"export module mayquill:{}.{};\n"
					"import std;\n"
					"import :definitions;\n"
					"export import :client_forward;\n\n",
					protocol.name, interface.name);

				for (auto& required_interface : interface.required_interfaces) {
					content += std::format("import :{}.{};\n", protocol.name, required_interface);
				}

				content += "export namespace mayquill {\n";
				content += std::format("struct {} {{\n"
                                       "    static constexpr std::string_view interface = \"{}\";\n"
									   "    static constexpr std::uint32_t version = {};\n\n"
									   "    Client& client;\n"
									   "    std::uint32_t id;\n"
									   "    void* user_data;\n",
					struct_name, interface.name, interface.version);

				// Write the custom enums the interface may define
				for (auto& wlenum : interface.enums) {
					content += std::format("\n    enum class {} {{\n", wlenum.name);

					for (auto& entry : wlenum.entries) {
						content += std::format("        {} = {},\n", entry.name, entry.value);
					}
					content += "    };\n";
				}

				// Write the request structs
				for (auto& request : interface.requests) {
					content += "   struct";
					content += discriminate_clang(std::format("   {}", request.annotation));
					content += std::format("    {} {{", request.name);

					for (auto& arg : request.arguments) {
						content += discriminate_clang(std::format("       {}", arg.annotation));
						content += std::format("       {} {};", arg.type, arg.name);
					}
					content += "\n    };\n";
				}

				// Only generate the requests & handle method, if any requests actually exist
				// If we didn't do this, we'd have an empty variant, which is invalid
				// This will however mean some structs do not have requests / handles, and so will need to be handled
				if (!interface.requests.empty()) {
					// Write the request variant
					content += "\n    using Request = std::variant<";

					for (std::size_t i = 0; i < interface.requests.size(); ++i) {
						content += interface.requests[i].name;
						if (i == interface.requests.size() - 1) {
							continue;
						}
						content += ", ";
					}
					content += ">;\n"
							   "    void handle(Request request); // Will be overidden by downstream user";
				}

				content += "\n    void handle_destroy();"
						   "\n    void destroy();";

				// Generate events
				for (std::size_t iter = 0; iter < interface.events.size(); ++iter) {
					auto& event = interface.events[iter];
					// Remember that events have no return type
					content += std::format("\n\n    void {}(", event.name);
					for (std::size_t i = 0; i < event.arguments.size(); ++i) {
						auto& argument = event.arguments[i];
						content += discriminate_clang(std::format("        {}", argument.annotation));
						content += std::format("        {} {}", argument.type, argument.name);
						if (i == event.arguments.size() - 1) {
							continue;
						}
						content += ", ";
					}
					if (event.arguments.size() > 0)
						content += "\n    ";
					content += ");\n";
				}

				content += "\n};\n};";
				write_file(interface.name + ".cppm", std::move(content));
			}

			// Write the implementation file
			{
				std::string content = "";
				add_header(content);
				content += "module;\n"
						   "#include <cassert>\n"
						   "module mayquill;\n"
						   "import :client;\n\n"
						   "namespace mayquill {\n";

				// Write event implementations
				for (std::size_t iter = 0; iter < interface.events.size(); ++iter) {
					auto& event = interface.events[iter];
					content += std::format("void {}::{}(", struct_name, event.name);
					for (std::size_t i = 0; i < event.arguments.size(); ++i) {
						auto& argument = event.arguments[i];
						content += std::format("{} {}", argument.type, argument.name);
						if (i == event.arguments.size() - 1) {
							continue;
						}
						content += ", ";
					}
					content += ") {";

					// Parameters can shadow the function name, so use full type specifier
					auto definition = std::format("    client.process_event<^^{}::{}, {}>(this->id ", struct_name, event.name, iter);
					for (auto& argument : event.arguments) {
						definition += std::format(", {}", argument.name);
					}
					definition += ");";
					content += discriminate_clang(definition);
					content += "}\n\n";
				}

				content += std::format("void {}::destroy() {{\n"
									   "   handle_destroy();\n"
									   "   assert(user_data == nullptr && \"{} did not clean up user data before destruction - was not nullptr\");\n"
									   "   client.remove_object(id);\n"
									   "}}\n\n",
					struct_name, struct_name);

				// Only generate a default unhandled handle method, if requests exist
				if (!interface.requests.empty()) {
					content += std::format(
						"// Default implementation, linker will prefer the implementation you provide, since we've marked this one as weak (absolutely ratioed)\n"
						"[[gnu::weak]]\n"
						"void {}::handle(Request request) {{\n"
						"    std::println(\"{}::handle(Request request) is currently unimplemented, request will be ignored\");\n"
						"}}\n",
						struct_name, struct_name, struct_name);
				}

				content += std::format(
					"\n[[gnu::weak]]\n"
					"void {}::handle_destroy() {{}}\n",
					struct_name);

				// Opt the bitfield enums into the bitfield operators
				for (auto& wlenum : interface.enums) {
					if (wlenum.bitfield) {
						content += std::format("\ntemplate<> constexpr bool enable_bitfield_operators<{}::{}> = true;", struct_name, wlenum.name);
					}
				}

				content += "};";

				// .cpp instead of .cppm as clang expects non-interface modules to not be called .cppm
				write_file(interface.name + "_impl.cpp", std::move(content));
			}
		}
	}
}
