#include <pugixml.hpp>
#include <string>
import std;

// The commenting format is made up, later we'll migrate to whatever clangd supports when it generates enough to test

/*
 *  Types:
 *  int / uint : 32 bits
 *  fixed point: 24 bits whole, 8 bits decimal
 *  object     : 32 bits
 *  new_id     : 32 bits
 *  string     : 32 bits integer length prefix, contents (n bits, padded to the nearest 32 bits), \0 terminator
 *  array      : 32 bits integer length prefix, contents (n bits, padded to the nearest 32 bits
 *  fd         : 0 bits, stored in ancillary data of the message
 *  enum       : 32 bits integer
 */
std::unordered_map<std::string, std::string> types = {
	{"int", "int32_t"},
	{"uint", "uint32_t"},
	{"fixed", "int32_t"},
	{"object", "uint32_t"},
	{"new_id", "uint32_t"},
	{"string", "std::string"},
	{"array", "void*"},
	{"fd", "int"},
	{"enum", "uint32_t"},
};

void handle_request(pugi::xml_node &request, std::string &out) {
	using Arg = struct {
		std::string name;
		std::string type;
		std::string summary;
	};
	std::vector<Arg> args;

	for (pugi::xml_node arg : request.children("arg")) {
		args.push_back(Arg{
			.name = arg.attribute("name").as_string(),
			.type = types[arg.attribute("type").as_string()],
			.summary = arg.attribute("summary").as_string(),
		});
	}

	std::format_to(
		std::back_inserter(out),
		"\n"
		"    /** {}\n"
		"     * {}\n",
		request.attribute("summary").as_string(),
		request.attribute("description").as_string());

	for (auto &arg : args) {
		std::format_to(
			std::back_inserter(out),
			"\n"
			"     * @var {} {}\n"
			"     * {}\n",
			arg.name,
			arg.type,
			arg.summary);
	}

	out += "     */\n";
}

// Prepends a prefix (shocked emoji) to the start of each line
std::string prepend(std::string target, const std::string &prefix) {
	target.insert(0, prefix);

	size_t pos = target.find('\n');

	while (pos != std::string::npos) {
		// Don't insert it after the last newline
		if (pos + 1 < target.size()) {
			target.insert(pos + 1, prefix);
		}

		pos = target.find('\n', pos + prefix.size() + 1);
	}

	return target;
}

// Trims all leading spaces, tabs from the start of each line.
std::string trim(std::string target) {
    size_t start = 0;

	while (start < target.size()) {
		auto end = start;

		while (end < target.size() && (target[end] == ' ' || target[end] == '\t')) {
			++end;
		}
		target.erase(start, end - start);

		size_t newline_pos = target.find('\n', start);
		// We've done every line
		if (newline_pos == std::string::npos) {
			break;
		}
		start = newline_pos + 1;
	}
    return target;
}

int main() {
	for (const auto &entry : std::filesystem::directory_iterator("./in")) {
		pugi::xml_document doc;
		pugi::xml_parse_result result = doc.load_file(entry.path().c_str());
		if (!result) {
			std::println("Failed to load document: {}, {}", entry.path().filename().c_str(), result.description());
			return -1;
		}

		std::string out = "";
		out += "/* Generated by MayQuill, godspeed */";

		for (pugi::xml_node interface : doc.child("protocol").children()) {
			auto description = interface.child("description");
			std::format_to(
				std::back_inserter(out),
				"\n\n"
				"/**\n"
				" * @brief {}\n"
				"{}"
				" */\n"
				"struct {} {{\n",
				description.attribute("summary").as_string(),
				prepend(trim(description.text().as_string()), " * "),
				interface.attribute("name").as_string());

			for (pugi::xml_node child : interface.children()) {
				std::string name = child.name();
				if (name == "request") {
					// handle_request(child, out);
				} else if (name == "event") {
				}
			}
			out += "}";
		}

		std::println("{}", out);
	}
}
