import std;
import Parser;

// // Prepends a prefix (shocked emoji) to the start of each line
// std::string prepend(std::string target, const std::string& prefix) {
// 	target.insert(0, prefix);

// 	size_t pos = target.find('\n');

// 	while (pos != std::string::npos) {
// 		// Don't insert it after the last newline
// 		if (pos + 1 < target.size()) {
// 			target.insert(pos + 1, prefix);
// 		}

// 		pos = target.find('\n', pos + prefix.size() + 1);
// 	}

// 	return target;
// }

// // Trims all leading spaces, tabs from the start of each line.
// std::string trim(std::string target) {
// 	size_t start = 0;

// 	while (start < target.size()) {
// 		auto end = start;

// 		while (end < target.size() && (target[end] == ' ' || target[end] == '\t')) {
// 			++end;
// 		}
// 		target.erase(start, end - start);

// 		size_t newline_pos = target.find('\n', start);
// 		// We've done every line
// 		if (newline_pos == std::string::npos) {
// 			break;
// 		}
// 		start = newline_pos + 1;
// 	}
// 	return target;
// }

std::string pascal_to_snake(std::string target) {
	target[0] = std::tolower(target[0]);
	for (int i = 1; i < target.length(); i++) {
		if (std::isupper(target[i])) {
			target[i] = std::tolower(target[i]);
			target.insert(i, 1, '_');
			i++; // skip the next one, because we just inserted there
		}
	}

	return target;
}

void add_header(std::string& target) {
	target += "/* Generated by MayQuill, godspeed */\n";
}

void write_file(std::string name, std::string content) {
	std::ofstream file(std::format("out/{}.cppm", pascal_to_snake(name)));
	std::print(file, "{}", content);
}

int main() {
	auto protocols = parser::get_protocols();

	// Write the MayQuill primary interface
	{
		std::string content = "";
		add_header(content);
		content += "export module MayQuill:Generated;\n"
				   "import std;\n";

		// Write the imports
		for (auto& protocol : protocols) {
			for (auto& interface : protocol.interfaces) {
				content += std::format("import {}.{};\n", protocol.name, interface.name);
			}
		}

		// Write the using Interface
		content += "\nusing Interface = std::variant<";
		for (auto& protocol : protocols) {
			for (std::size_t i = 0; i < protocol.interfaces.size(); ++i) {
				content += protocol.interfaces[i].name;
				if (i == protocol.interfaces.size() - 1) {
					continue;
				}
				content += ", ";
			}
		}
		content += ">;\n";
		write_file("mayquill", std::move(content));
	}

	// Write the individual interfaces
	for (auto& protocol : protocols) {
		for (auto& interface : protocol.interfaces) {
			std::string content = "";
			add_header(content);
			content += std::format(
				// "module;\n"
				"export module {}.{};\n"
				"import std;\n\n",
				protocol.name, interface.name);

			// content += std::format("export namespace {} {{\n", protocol.name);
			content += std::format("export struct {} {{\n"
								   "    // These are the only runtime mutable states\n"
								   "    std::uint32_t object_id;\n"
								   "    std::uint32_t client_id;\n\n",
				interface.name);

			for (auto& request : interface.requests) {
				content += std::format("    struct {} {{", request.name);

				for (auto& arg : request.arguments) {
					// TODO, full arg parsing
					content += std::format(" {} {};", arg.type, arg.name);
				}
				content += " };\n";
			}

			content += "\n";
			content += "    using Request = std::variant<";

			for (std::size_t i = 0; i < interface.requests.size(); ++i) {
				content += interface.requests[i].name;
				if (i == interface.requests.size() - 1) {
					continue;
				}
				content += ", ";
			}
			content += ">;\n"
					   "    void handle(Request request); // Will be overidden by downstream user\n"
					   "};\n";
			// "};";

			write_file(interface.name, std::move(content));
		}
	}
}
