import std;
import Parser;

// // Prepends a prefix (shocked emoji) to the start of each line
// std::string prepend(std::string target, const std::string& prefix) {
// 	target.insert(0, prefix);

// 	size_t pos = target.find('\n');

// 	while (pos != std::string::npos) {
// 		// Don't insert it after the last newline
// 		if (pos + 1 < target.size()) {
// 			target.insert(pos + 1, prefix);
// 		}

// 		pos = target.find('\n', pos + prefix.size() + 1);
// 	}

// 	return target;
// }

// // Trims all leading spaces, tabs from the start of each line.
// std::string trim(std::string target) {
// 	size_t start = 0;

// 	while (start < target.size()) {
// 		auto end = start;

// 		while (end < target.size() && (target[end] == ' ' || target[end] == '\t')) {
// 			++end;
// 		}
// 		target.erase(start, end - start);

// 		size_t newline_pos = target.find('\n', start);
// 		// We've done every line
// 		if (newline_pos == std::string::npos) {
// 			break;
// 		}
// 		start = newline_pos + 1;
// 	}
// 	return target;
// }

std::string pascal_to_snake(std::string target) {
	target[0] = std::tolower(target[0]);
	for (int i = 1; i < target.length(); i++) {
		if (std::isupper(target[i])) {
			target[i] = std::tolower(target[i]);
			target.insert(i, 1, '_');
			i++; // skip the next one, because we just inserted there
		}
	}

	return target;
}

void add_header(std::string& target) {
	target += "/* Generated by MayQuill, godspeed */\n\n";
}

void write_file(std::string name, std::string content) {
	std::ofstream file(std::format("out/{}.cppm", pascal_to_snake(name)));
	std::print(file, "{}", content);
}

int main() {
	auto protocols = parser::get_protocols();

	// Write the actual server
	{
		std::string content = "";
		add_header(content);
		content += "export module MayQuill;\n\n";
		for (auto& protocol : protocols) {
		}

		// write_file(protocol.name, std::move(content));
	}

	// Write the individual interfaces
	for (auto& protocol : protocols) {
		for (auto& interface : protocol.interfaces) {
			std::string content = "";
			add_header(content);

            content += std::format("struct {} {{\n", interface.name);
		}
	}
}
